### PR TITLE
Fix modal positioning in Safari

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Fixes https://github.com/picnicss/picnic/issues/40.

I believe this does the trick, though I figured out this fix just by editing in Safari's inspector and don't have the time or dev setup to compile the scss myself.

### CODE REVIEW

**Comment by galulex** [comment]
@JacobEvelyn There is autoprefixer [dependency](https://github.com/picnicss/picnic/blob/master/gulpfile.js#L17). We can specify the versions of browser we want to support and prefixes are added automatically. Correct me if i am wrong

**Comment by JacobEvelyn** [comment]
Ah, didn't notice that. That's strange, since I'm on the latest version of Safari. Does autoprefixer get used for the separate plugin builds? That might be the issue.

**Comment by franciscop** [comment]
Confirmed by searching for `-webkit-transform` in the diff of the minified files, `-webkit-transform` is not being added to the source but it is being added when you write it manually (as expected). 

Seems to be an issue on autoprefixer package as [caniuse.com lists `transforms` for safari as needing -webkit- even for the latest version](http://caniuse.com/#feat=transforms2d).

**Comment by franciscop** [comment]
From reading [this issue in autoprefixer package](https://github.com/postcss/autoprefixer/issues/431) and [using the interactive demo](http://simevidas.jsbin.com/gufoko/quiet), the problem might be somewhere else.

**Comment by franciscop** [comment]
Yes, the problem is that right now there are two build methods, one that uses the gulpfile.js (as it should) and one that uses a [wacky implementation for generating the `/nut` files](https://github.com/picnicss/picnic/blob/master/web/controller.js). The latest one is [going to be abandoned](https://github.com/picnicss/picnic/issues/39) in favour of the current picnic.css in jsdelivr, bower for those who want the flexibility that plugins allow, likely a full.css with all of the plugins and unlikely but possible each plugin might have its own plugin.css.

Still, I keep this pull but add a note to the migration issue for deleting it, since it might be a couple of months until I get the time for properly fix it.

**Comment by JacobEvelyn** [comment]
Just noting that I'm not sure you meant to merge all of my commits (see how the diff https://github.com/picnicss/picnic/commit/70fc3033fcd8e9b464390234c448019154f8a403 includes both the original `.scss` fix and some hacky experimentation on my part). Looks like I accidentally committed to a my master branch instead of a separate one. Sorry!

**Comment by franciscop** [comment]
I'm not sure what you mean, in the diff [70fc303](https://github.com/picnicss/picnic/commit/70fc3033fcd8e9b464390234c448019154f8a403) the only changes in the .scss that I can see are the two additions of `-webkit-` in lines 45 and 71 of `plugins/modal/_v2.scss`, which perfectly fixes the issue.

There's also a compressed `web/nut/raw+modal_2_jacob.min.css`, but that's not really an issue. So, where did you do the experimentation? In which file/line? Because in that diff I cannot really see anything else... (also I'm still getting the hang of git, so sorry if I missed any other file, but I couldn't find any).

**Comment by JacobEvelyn** [comment]
If you look at the diff (https://github.com/picnicss/picnic/commit/70fc3033fcd8e9b464390234c448019154f8a403) you can see that three files have been changed: the original `.scss`, my hacky `web/nut/raw+modal_2_jacob.min.css`, and some experimentation I did on `releases/plugins.min.css`. I don't know enough about how the `releases` files work to know if that last one is bad or harmless, but in the interest of keeping this project clean I think it makes sense to remove (or at least rename) the `nut` file and think about whether the `releases` one should be changed.

Since I was just playing around, I didn't make sure that, for example, `releases/plugins.min.css` matches the non-minified version (``releases/plugins.css`).

I'm happy to help you with `git` as best as I can!

**Comment by franciscop** [comment]
Oh I see. However, right now the only important file in `/releases` is `picnic.min.css` as it's included in bower. Even so, both `picnic.min.css` and `plugins.min.css` are overwritten constantly thanks to Gulp, so any change made manually should be overwritten already. I could see that there was a difference in the `.css` but I didn't compare the code beyond checking that `-webkit-` was added in there since I thought that the rest was autogenerated from the new scss. I will be more careful in the future.

> I don't know enough about how the releases files work to know if that last one is bad or harmless

Truth be told, the code base is quite confusing right now: there are many files with no purpose, duplicated files, etc. That's why [I'm deprecating a large portion of the code](https://github.com/picnicss/picnic/issues/39), including a clean up of these files which should make it much easier to understand everything.

**Comment by JacobEvelyn** [comment]
Got it, thanks. And :+1: to the codebase cleanup.

**Pull request merged**
