### PR TITLE
Fixed min css broken link issue.

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by franciscop** [comment]
Did they really change the domain without a proper redirect? :-(

If you are part of the project, please make sure that minfwk.com redirects to mincss.com, probably with a permanent redirect.

**Comment by kunagpal** [comment]
Well yes, minfwk.com appears quite implicit, as compared to mincss.com. In any case, I am not part of the project, I was just passing by, so to speak.

**Comment by owenversteeg** [comment]
Hey - I'm the creator of Min. The domain was changed a while back (1.5 years ago) and originally it was a 301 redirect but somehow that broke a while back. I've changed it back to a 301 which should hopefully work. Thanks for the heads-up!

**Comment by franciscop** [comment]
No problem! :smile:

**Pull request merged**
